// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjrYRheSUY9VbcMPAxFJBFsYe5hNY9u4',
    appId: '1:279506425554:web:c34946c91da065e3c93f0b',
    messagingSenderId: '279506425554',
    projectId: 'home-here-2025',
    authDomain: 'home-here-2025.firebaseapp.com',
    storageBucket: 'home-here-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqnAxpLciiE0nO2iQnzNOitHZAHJ0d39A',
    appId: '1:279506425554:android:51b8eec44484b769c93f0b',
    messagingSenderId: '279506425554',
    projectId: 'home-here-2025',
    storageBucket: 'home-here-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrZ8FtQvffVytjmIgm9dV3oO31U-datM',
    appId: '1:279506425554:ios:c4497c29317d5dbbc93f0b',
    messagingSenderId: '279506425554',
    projectId: 'home-here-2025',
    storageBucket: 'home-here-2025.firebasestorage.app',
    iosBundleId: 'com.example.homeHere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrZ8FtQvffVytjmIgm9dV3oO31U-datM',
    appId: '1:279506425554:ios:c4497c29317d5dbbc93f0b',
    messagingSenderId: '279506425554',
    projectId: 'home-here-2025',
    storageBucket: 'home-here-2025.firebasestorage.app',
    iosBundleId: 'com.example.homeHere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjrYRheSUY9VbcMPAxFJBFsYe5hNY9u4',
    appId: '1:279506425554:web:b135dd0954bcb5d7c93f0b',
    messagingSenderId: '279506425554',
    projectId: 'home-here-2025',
    authDomain: 'home-here-2025.firebaseapp.com',
    storageBucket: 'home-here-2025.firebasestorage.app',
  );
}
